# Generated by Django 5.0.4 on 2024-04-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_vedio",
            field=models.URLField(default=1),
        ),
    ]
